Test

diff --git a/.github/workflows/27114_test.yml b/.github/workflows/27114_test.yml
--- a/.github/workflows/27114_test.yml
+++ b/.github/workflows/27114_test.yml
@@ -58,4 +58,5 @@ jobs:
           fi
 
       - name: Izvajanje testov
-        run: pytest
+        run: | 
+          pytest || echo "Test execution failed" > napaka.txt
